; NEWCHARACTER.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

; SECTION "Tiles", HOME

; Start of tile array.
SECTION "Character", ROMX, bank[3]
Character::
DB $C3,$C3,$C3,$42,$7E,$7E,$FF,$81
DB $FF,$81,$FF,$81,$7E,$7E,$24,$24
DB $C3,$C3,$C3,$42,$7E,$7E,$FF,$81
DB $FF,$A5,$FF,$81,$7E,$7E,$24,$24
DB $18,$18,$18,$08,$3C,$3C,$7E,$42
DB $7E,$52,$7E,$42,$3C,$3C,$24,$24
DB $18,$18,$18,$10,$3C,$3C,$7E,$42
DB $7E,$4A,$7E,$42,$3C,$3C,$24,$24
DB $20,$20,$30,$30,$38,$38,$3C,$3C
DB $3C,$3C,$38,$38,$30,$30,$20,$20
DB $FF,$DF,$FF,$CF,$FF,$C7,$FF,$C3
DB $FF,$C3,$FF,$C7,$FF,$CF,$FF,$DF


Chest::
DB $FF,$FF,$81,$FF,$81,$FF,$FF,$E7
DB $99,$E7,$81,$FF,$81,$FF,$FF,$FF
DB $00,$42,$00,$42,$00,$81,$00,$81
DB $00,$81,$00,$42,$00,$42,$00,$C3
; End of NEWCHARACTER.Z80
